accessibility: protected
containerPort: 5000

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 1
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: 5000
  periodSeconds: 5

## scaling ##
autoscale: enabled
replicas: 1 # the desired number of replicas to start with
minReplicas: 1 # minimum number of replicas
maxReplicas: 32 # max number of replicas
cpuThreshold: "0"
memoryThreshold: "30"
